Add specific route only for ping
ping utility does not need to set route for forward packets via specific interface.

diff --git a/omr-tracker/files/bin/omr-tracker b/omr-tracker/files/bin/omr-tracker
--- a/omr-tracker/files/bin/omr-tracker
+++ b/omr-tracker/files/bin/omr-tracker
@@ -217,25 +217,27 @@ while true; do
 						config_foreach _ping_server server $OMR_TRACKER_DEVICE
 					fi
 					if [ "$serverip_ping" = false ]; then
-						# Check if route is not used
-						while ! ip route add $OMR_TRACKER_HOST via $OMR_TRACKER_DEVICE_GATEWAY dev $OMR_TRACKER_DEVICE src $OMR_TRACKER_DEVICE_IP > /dev/null 2&>1
-						do
-							logger -t "omr-tracker" "Can't create route to $OMR_TRACKER_HOST via $OMR_TRACKER_DEVICE_GATEWAY dev $OMR_TRACKER_DEVICE src $OMR_TRACKER_DEVICE_IP. waiting..."
-							sleep 2
-							ip route del "$OMR_TRACKER_HOST" via "$OMR_TRACKER_DEVICE_GATEWAY" dev "$OMR_TRACKER_DEVICE" src "$OMR_TRACKER_DEVICE_IP" > /dev/null 2&>1
-							_restart
-						done
 						if [ "$OMR_TRACKER_TYPE" = "ping" ]; then
 							_ping "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE" "yes"
 							statusb=$?
-						elif [ "$OMR_TRACKER_TYPE" = "httping" ]; then
-							_httping "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE_IP" "yes"
-							statusb=$?
-						elif [ "$OMR_TRACKER_TYPE" = "dns" ]; then
-							_dns "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE_IP" "yes"
-							statusb=$?
+						else
+							# Check if route is not used
+							while ! ip route add $OMR_TRACKER_HOST via $OMR_TRACKER_DEVICE_GATEWAY dev $OMR_TRACKER_DEVICE src $OMR_TRACKER_DEVICE_IP > /dev/null 2&>1
+							do
+								logger -t "omr-tracker" "Can't create route to $OMR_TRACKER_HOST via $OMR_TRACKER_DEVICE_GATEWAY dev $OMR_TRACKER_DEVICE src $OMR_TRACKER_DEVICE_IP. waiting..."
+								sleep 2
+								ip route del "$OMR_TRACKER_HOST" via "$OMR_TRACKER_DEVICE_GATEWAY" dev "$OMR_TRACKER_DEVICE" src "$OMR_TRACKER_DEVICE_IP" > /dev/null 2&>1
+								_restart
+							done
+							if [ "$OMR_TRACKER_TYPE" = "httping" ]; then
+								_httping "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE_IP" "yes"
+								statusb=$?
+							elif [ "$OMR_TRACKER_TYPE" = "dns" ]; then
+								_dns "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE_IP" "yes"
+								statusb=$?
+							fi
+							ip route del "$OMR_TRACKER_HOST" via "$OMR_TRACKER_DEVICE_GATEWAY" dev "$OMR_TRACKER_DEVICE" src "$OMR_TRACKER_DEVICE_IP" > /dev/null 2&>1
 						fi
-						ip route del "$OMR_TRACKER_HOST" via "$OMR_TRACKER_DEVICE_GATEWAY" dev "$OMR_TRACKER_DEVICE" src "$OMR_TRACKER_DEVICE_IP" > /dev/null 2&>1
 						if $(exit $statusb); then
 							OMR_TRACKER_STATUS_MSG=""
 							OMR_TRACKER_STATUS="OK"
