Fix when interface down

diff --git a/omr-tracker/files/bin/omr-tracker b/omr-tracker/files/bin/omr-tracker
--- a/omr-tracker/files/bin/omr-tracker
+++ b/omr-tracker/files/bin/omr-tracker
@@ -177,119 +177,123 @@ while true; do
 	OMR_TRACKER_DEVICE_GATEWAY=
 	serverip_ping=false
 
-	if [ -d "/sys/class/net/$OMR_TRACKER_DEVICE" ] && [ -n "$(ip link show $OMR_TRACKER_DEVICE | grep UP)" ]; then
-		# retrieve iface ip and gateway
-		OMR_TRACKER_DEVICE_IP=$(ip -4 -br addr ls dev "$OMR_TRACKER_DEVICE" | awk -F'[ /]+' '{print $3}')
-		if [ -z "$OMR_TRACKER_DEVICE_IP" ]; then
-			OMR_TRACKER_DEVICE_IP=$(ip -4 addr show dev "$OMR_TRACKER_DEVICE" | grep -m 1 inet | awk '{print $2}' | cut -d'/' -s -f1)
-		fi
-		#OMR_TRACKER_DEVICE_IP=$(ubus call network.interface.$OMR_TRACKER_INTERFACE status | jsonfilter -e '@["ipv4-address"][0].address' | tr -d "\n")
-		#if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
-		#	OMR_TRACKER_DEVICE_GATEWAY=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | grep -v default | awk '/proto static/ {print $1}' | tr -d "\n")
-		#fi
-		if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
-			OMR_TRACKER_DEVICE_GATEWAY=$(uci -q get "network.$OMR_TRACKER_INTERFACE.gateway")
-		fi
-		if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ] || [ "$OMR_TRACKER_DEVICE_GATEWAY" = "0.0.0.0" ]; then
-			OMR_TRACKER_DEVICE_GATEWAY=$(ubus call network.interface.$OMR_TRACKER_INTERFACE status | jsonfilter -q -l 1 -e '@.inactive.route[@.target="0.0.0.0"].nexthop' | tr -d "\n")
-		fi
-		if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ] || [ "$OMR_TRACKER_DEVICE_GATEWAY" = "0.0.0.0" ]; then
-			OMR_TRACKER_DEVICE_GATEWAY=$(ubus call network.interface.$OMR_TRACKER_INTERFACE status | jsonfilter -q -l 1 -e '@.route[@.target="0.0.0.0"].nexthop' | tr -d "\n")
-		fi
-		if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ] || [ "$OMR_TRACKER_DEVICE_GATEWAY" = "0.0.0.0" ]; then
-			OMR_TRACKER_DEVICE_GATEWAY=$(ubus call network.interface.${OMR_TRACKER_INTERFACE}_4 status 2>/dev/null | jsonfilter -q -l 1 -e '@.inactive.route[@.target="0.0.0.0"].nexthop' | tr -d "\n")
-		fi
-		if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ] || [ "$OMR_TRACKER_DEVICE_GATEWAY" = "0.0.0.0" ]; then
-			if [ "$OMR_TRACKER_INTERFACE" = "omrvpn" ] && [ "$(uci -q get glorytun.vpn.enable)" = "1" ]; then
-				OMR_TRACKER_DEVICE_GATEWAY=$(uci -q get glorytun.vpn.remoteip)
-			else
-				OMR_TRACKER_DEVICE_GATEWAY=""
+	if [ -d "/sys/class/net/$OMR_TRACKER_DEVICE" ]; then
+		if [ -n "$(ip link show $OMR_TRACKER_DEVICE | grep UP)" ]; then
+			# retrieve iface ip and gateway
+			OMR_TRACKER_DEVICE_IP=$(ip -4 -br addr ls dev "$OMR_TRACKER_DEVICE" | awk -F'[ /]+' '{print $3}')
+			if [ -z "$OMR_TRACKER_DEVICE_IP" ]; then
+				OMR_TRACKER_DEVICE_IP=$(ip -4 addr show dev "$OMR_TRACKER_DEVICE" | grep -m 1 inet | awk '{print $2}' | cut -d'/' -s -f1)
 			fi
-		fi
-		if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
-			OMR_TRACKER_DEVICE_ROUTE=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | grep via | grep -v default | grep -v metric | grep -v / | awk '{print $1; exit}' | tr -d "\n")
-		fi
-		if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
-			OMR_TRACKER_DEVICE_GATEWAY=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | grep kernel | awk '/proto kernel/ {print $1}' | tr -d "\n")
-		fi
-
-		# execute specific tracker
-		if [ -n "$OMR_TRACKER_DEVICE_IP" ] && [ -n "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
-			# setup loop variable
-			tries="$OMR_TRACKER_TRIES"
-			# loop until tries attempts have been reached
-			while [ "$tries" -gt 0 ]; do
-				if [ -n "$OMR_TRACKER_DEVICE_ROUTE" ]; then
-					_ping "$OMR_TRACKER_DEVICE_ROUTE" "$OMR_TRACKER_DEVICE" "no"
-					status=$?
+			#OMR_TRACKER_DEVICE_IP=$(ubus call network.interface.$OMR_TRACKER_INTERFACE status | jsonfilter -e '@["ipv4-address"][0].address' | tr -d "\n")
+			#if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
+			#	OMR_TRACKER_DEVICE_GATEWAY=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | grep -v default | awk '/proto static/ {print $1}' | tr -d "\n")
+			#fi
+			if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
+				OMR_TRACKER_DEVICE_GATEWAY=$(uci -q get "network.$OMR_TRACKER_INTERFACE.gateway")
+			fi
+			if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ] || [ "$OMR_TRACKER_DEVICE_GATEWAY" = "0.0.0.0" ]; then
+				OMR_TRACKER_DEVICE_GATEWAY=$(ubus call network.interface.$OMR_TRACKER_INTERFACE status | jsonfilter -q -l 1 -e '@.inactive.route[@.target="0.0.0.0"].nexthop' | tr -d "\n")
+			fi
+			if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ] || [ "$OMR_TRACKER_DEVICE_GATEWAY" = "0.0.0.0" ]; then
+				OMR_TRACKER_DEVICE_GATEWAY=$(ubus call network.interface.$OMR_TRACKER_INTERFACE status | jsonfilter -q -l 1 -e '@.route[@.target="0.0.0.0"].nexthop' | tr -d "\n")
+			fi
+			if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ] || [ "$OMR_TRACKER_DEVICE_GATEWAY" = "0.0.0.0" ]; then
+				OMR_TRACKER_DEVICE_GATEWAY=$(ubus call network.interface.${OMR_TRACKER_INTERFACE}_4 status 2>/dev/null | jsonfilter -q -l 1 -e '@.inactive.route[@.target="0.0.0.0"].nexthop' | tr -d "\n")
+			fi
+			if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ] || [ "$OMR_TRACKER_DEVICE_GATEWAY" = "0.0.0.0" ]; then
+				if [ "$OMR_TRACKER_INTERFACE" = "omrvpn" ] && [ "$(uci -q get glorytun.vpn.enable)" = "1" ]; then
+					OMR_TRACKER_DEVICE_GATEWAY=$(uci -q get glorytun.vpn.remoteip)
 				else
-					_ping "$OMR_TRACKER_DEVICE_GATEWAY" "$OMR_TRACKER_DEVICE" "no"
-					status=$?
+					OMR_TRACKER_DEVICE_GATEWAY=""
 				fi
-				if $(exit $status) && [ "$OMR_TRACKER_TYPE" = "none" ]; then
-					OMR_TRACKER_STATUS_MSG=""
-					OMR_TRACKER_STATUS="OK"
-					break
-				elif [ "$OMR_TRACKER_TYPE" != "none" ]; then
-					if ! $(exit $status); then
-						OMR_TRACKER_STATUS_MSG="gateway down"
-					fi
-					serverip_ping=false
-					if [ "$OMR_TRACKER_TYPE" = "ping" ]; then
-						config_load openmptcprouter
-						config_foreach _ping_server server $OMR_TRACKER_DEVICE
-					fi
-					if [ "$serverip_ping" = false ] && [ -n "$OMR_TRACKER_HOST" ]; then
-						OMR_TRACKER_HOST=$(resolveip -4 $OMR_TRACKER_HOST | tr -d "\n")
-						if [ "$(uci -q get network.$OMR_TRACKER_INTERFACE.proto)" = "3g" ] || [ "$(uci -q get network.$OMR_TRACKER_INTERFACE.proto)" = "qmi" ] || [ "$(uci -q get network.$OMR_TRACKER_INTERFACE.proto)" = "ncm" ]; then
-							# Check if route is not used
-							while ! ip route add $OMR_TRACKER_HOST via $OMR_TRACKER_DEVICE_GATEWAY dev $OMR_TRACKER_DEVICE src $OMR_TRACKER_DEVICE_IP > /dev/null 2>&1
-							do
-								logger -t "omr-tracker" "Can't create route to $OMR_TRACKER_HOST via $OMR_TRACKER_DEVICE_GATEWAY dev $OMR_TRACKER_DEVICE src $OMR_TRACKER_DEVICE_IP. waiting..."
-								sleep 2
-								ip route del "$OMR_TRACKER_HOST" via "$OMR_TRACKER_DEVICE_GATEWAY" dev "$OMR_TRACKER_DEVICE" src "$OMR_TRACKER_DEVICE_IP" > /dev/null 2>&1
-								_restart
-							done
-						fi
-						if [ "$OMR_TRACKER_TYPE" = "ping" ]; then
-							_ping "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE" "yes"
-							statusb=$?
-						elif [ "$OMR_TRACKER_TYPE" = "httping" ]; then
-							_httping "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE_IP" "yes"
-							statusb=$?
-						elif [ "$OMR_TRACKER_TYPE" = "dns" ]; then
-							_dns "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE_IP" "yes"
-							statusb=$?
-						fi
-						ip route del "$OMR_TRACKER_HOST" via "$OMR_TRACKER_DEVICE_GATEWAY" dev "$OMR_TRACKER_DEVICE" src "$OMR_TRACKER_DEVICE_IP" > /dev/null 2>&1
-						if $(exit $statusb); then
-							OMR_TRACKER_STATUS_MSG=""
-							OMR_TRACKER_STATUS="OK"
-							break
-						else
-							if [ "$OMR_TRACKER_LIST_HOSTS" = "" ]; then
-								OMR_TRACKER_LIST_HOSTS="$OMR_TRACKER_HOST"
-							else
-								OMR_TRACKER_LIST_HOSTS="$OMR_TRACKER_LIST_HOSTS,$OMR_TRACKER_HOST"
-							fi
-						fi
+			fi
+			if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
+				OMR_TRACKER_DEVICE_ROUTE=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | grep via | grep -v default | grep -v metric | grep -v / | awk '{print $1; exit}' | tr -d "\n")
+			fi
+			if [ -z "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
+				OMR_TRACKER_DEVICE_GATEWAY=$(ip -4 r list dev "$OMR_TRACKER_DEVICE" | grep kernel | awk '/proto kernel/ {print $1}' | tr -d "\n")
+			fi
+
+			# execute specific tracker
+			if [ -n "$OMR_TRACKER_DEVICE_IP" ] && [ -n "$OMR_TRACKER_DEVICE_GATEWAY" ]; then
+				# setup loop variable
+				tries="$OMR_TRACKER_TRIES"
+				# loop until tries attempts have been reached
+				while [ "$tries" -gt 0 ]; do
+					if [ -n "$OMR_TRACKER_DEVICE_ROUTE" ]; then
+						_ping "$OMR_TRACKER_DEVICE_ROUTE" "$OMR_TRACKER_DEVICE" "no"
+						status=$?
 					else
+						_ping "$OMR_TRACKER_DEVICE_GATEWAY" "$OMR_TRACKER_DEVICE" "no"
+						status=$?
+					fi
+					if $(exit $status) && [ "$OMR_TRACKER_TYPE" = "none" ]; then
 						OMR_TRACKER_STATUS_MSG=""
 						OMR_TRACKER_STATUS="OK"
 						break
+					elif [ "$OMR_TRACKER_TYPE" != "none" ]; then
+						if ! $(exit $status); then
+							OMR_TRACKER_STATUS_MSG="gateway down"
+						fi
+						serverip_ping=false
+						if [ "$OMR_TRACKER_TYPE" = "ping" ]; then
+							config_load openmptcprouter
+							config_foreach _ping_server server $OMR_TRACKER_DEVICE
+						fi
+						if [ "$serverip_ping" = false ] && [ -n "$OMR_TRACKER_HOST" ]; then
+							OMR_TRACKER_HOST=$(resolveip -4 $OMR_TRACKER_HOST | tr -d "\n")
+							if [ "$(uci -q get network.$OMR_TRACKER_INTERFACE.proto)" = "3g" ] || [ "$(uci -q get network.$OMR_TRACKER_INTERFACE.proto)" = "qmi" ] || [ "$(uci -q get network.$OMR_TRACKER_INTERFACE.proto)" = "ncm" ]; then
+								# Check if route is not used
+								while ! ip route add $OMR_TRACKER_HOST via $OMR_TRACKER_DEVICE_GATEWAY dev $OMR_TRACKER_DEVICE src $OMR_TRACKER_DEVICE_IP > /dev/null 2>&1
+								do
+									logger -t "omr-tracker" "Can't create route to $OMR_TRACKER_HOST via $OMR_TRACKER_DEVICE_GATEWAY dev $OMR_TRACKER_DEVICE src $OMR_TRACKER_DEVICE_IP. waiting..."
+									sleep 2
+									ip route del "$OMR_TRACKER_HOST" via "$OMR_TRACKER_DEVICE_GATEWAY" dev "$OMR_TRACKER_DEVICE" src "$OMR_TRACKER_DEVICE_IP" > /dev/null 2>&1
+									_restart
+								done
+							fi
+							if [ "$OMR_TRACKER_TYPE" = "ping" ]; then
+								_ping "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE" "yes"
+								statusb=$?
+							elif [ "$OMR_TRACKER_TYPE" = "httping" ]; then
+								_httping "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE_IP" "yes"
+								statusb=$?
+							elif [ "$OMR_TRACKER_TYPE" = "dns" ]; then
+								_dns "$OMR_TRACKER_HOST" "$OMR_TRACKER_DEVICE_IP" "yes"
+								statusb=$?
+							fi
+							ip route del "$OMR_TRACKER_HOST" via "$OMR_TRACKER_DEVICE_GATEWAY" dev "$OMR_TRACKER_DEVICE" src "$OMR_TRACKER_DEVICE_IP" > /dev/null 2>&1
+							if $(exit $statusb); then
+								OMR_TRACKER_STATUS_MSG=""
+								OMR_TRACKER_STATUS="OK"
+								break
+							else
+								if [ "$OMR_TRACKER_LIST_HOSTS" = "" ]; then
+									OMR_TRACKER_LIST_HOSTS="$OMR_TRACKER_HOST"
+								else
+									OMR_TRACKER_LIST_HOSTS="$OMR_TRACKER_LIST_HOSTS,$OMR_TRACKER_HOST"
+								fi
+							fi
+						else
+							OMR_TRACKER_STATUS_MSG=""
+							OMR_TRACKER_STATUS="OK"
+							break
+						fi
+					elif ! $(exit $status); then
+						OMR_TRACKER_STATUS_MSG="gateway down"
 					fi
-				elif ! $(exit $status); then
-					OMR_TRACKER_STATUS_MSG="gateway down"
-				fi
-				tries=$((tries - 1))
-				#_restart
-				OMR_TRACKER_HOST="${OMR_TRACKER_HOSTS%% *}"
-				[ "$OMR_TRACKER_HOST" = "$OMR_TRACKER_HOSTS" ] || {
-					OMR_TRACKER_HOSTS="${OMR_TRACKER_HOSTS#* } $OMR_TRACKER_HOST"
-				}
-				#OMR_TRACKER_TIMEOUT=$((OMR_TRACKER_TIMEOUT * 2))
-				sleep "$OMR_TRACKER_INTERVAL_TRIES"
-			done
+					tries=$((tries - 1))
+					#_restart
+					OMR_TRACKER_HOST="${OMR_TRACKER_HOSTS%% *}"
+					[ "$OMR_TRACKER_HOST" = "$OMR_TRACKER_HOSTS" ] || {
+						OMR_TRACKER_HOSTS="${OMR_TRACKER_HOSTS#* } $OMR_TRACKER_HOST"
+					}
+					#OMR_TRACKER_TIMEOUT=$((OMR_TRACKER_TIMEOUT * 2))
+					sleep "$OMR_TRACKER_INTERVAL_TRIES"
+				done
+			fi
+		else
+			OMR_TRACKER_STATUS_MSG="link down"
 		fi
 	fi
 
