Update bcm27xx-eeprom chmod patch

diff --git a/bcm27xx-eeprom/patches/0004-rpi-eeprom-update-remove-chmod.patch b/bcm27xx-eeprom/patches/0004-rpi-eeprom-update-remove-chmod.patch
--- a/bcm27xx-eeprom/patches/0004-rpi-eeprom-update-remove-chmod.patch
+++ b/bcm27xx-eeprom/patches/0004-rpi-eeprom-update-remove-chmod.patch
@@ -1,20 +1,24 @@
---- a/rpi-eeprom-update	2020-08-23 10:36:21.892002253 +0200
-+++ b/rpi-eeprom-update	2020-08-23 10:36:41.819672745 +0200
-@@ -166,7 +166,7 @@
+--- a/rpi-eeprom-update	2020-11-05 21:58:02.247836497 +0100
++++ b/rpi-eeprom-update	2020-11-05 21:58:36.911266307 +0100
+@@ -186,8 +186,8 @@
                  || die "Failed to copy ${TMP_EEPROM_IMAGE} to ${BOOTFS}"
  
          # For NFS mounts ensure that the files are readable to the TFTP user
--        chmod -f go+r "${BOOTFS}/pieeprom.upd" "${BOOTFS}/pieeprom.sig"
-+        #chmod -f go+r "${BOOTFS}/pieeprom.upd" "${BOOTFS}/pieeprom.sig"
+-        chmod -f go+r "${BOOTFS}/pieeprom.upd" "${BOOTFS}/pieeprom.sig" \
+-                || die "Failed to set permissions on eeprom update files"
++        #chmod -f go+r "${BOOTFS}/pieeprom.upd" "${BOOTFS}/pieeprom.sig" \
++        #        || die "Failed to set permissions on eeprom update files"
     fi
  
     if [ -n "${VL805_UPDATE_IMAGE}" ]; then
-@@ -175,7 +175,7 @@
-         cp -f "${VL805_UPDATE_IMAGE}" "${BOOTFS}/vl805.bin"
+@@ -198,8 +198,8 @@
+                 || die "Failed to copy ${VL805_UPDATE_IMAGE} to ${BOOTFS}/vl805.bin"
  
          # For NFS mounts ensure that the files are readable to the TFTP user
--        chmod -f go+r "${BOOTFS}/vl805.bin" "${BOOTFS}/vl805.sig"
-+        #chmod -f go+r "${BOOTFS}/vl805.bin" "${BOOTFS}/vl805.sig"
+-        chmod -f go+r "${BOOTFS}/vl805.bin" "${BOOTFS}/vl805.sig" \
+-                || die "Failed to set permissions on eeprom update files"
++        #chmod -f go+r "${BOOTFS}/vl805.bin" "${BOOTFS}/vl805.sig" \
++        #        || die "Failed to set permissions on eeprom update files"
     fi
  
     cp -f "${RECOVERY_BIN}" "${BOOTFS}/recovery.bin" \
